# Generated by Django 6.0.6 on 2026-06-19 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRecipe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("equipment_notes", models.TextField(blank=True)),
                ("prep_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("cook_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="collection/"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="RecipeBoxItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "ordering": ["recipe__title"],
            },
        ),
        migrations.CreateModel(
            name="CollectionIngredientLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("teaspoon", "teaspoon"),
                            ("tablespoon", "tablespoon"),
                            ("fluid_ounce", "fluid ounce"),
                            ("cup", "cup"),
                            ("quart", "quart"),
                            ("gallon", "gallon"),
                            ("milliliter", "milliliter"),
                            ("liter", "liter"),
                            ("pound", "pound"),
                            ("ounce", "ounce"),
                            ("milligram", "milligram"),
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("inch", "inch"),
                            ("centimeter", "centimeter"),
                            ("whole", "whole"),
                        ],
                        max_length=32,
                    ),
                ),
                ("custom_unit", models.CharField(blank=True, max_length=64)),
                ("prep_note", models.CharField(blank=True, max_length=255)),
                ("substitution_note", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_lines",
                        to="catalog.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
