# Generated by Django 6.0.6 on 2026-06-19 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        ("development", "0001_initial"),
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrecipe",
            name="fork_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_recipe",
                to="development.recipefork",
            ),
        ),
        migrations.AddField(
            model_name="collectionrecipe",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_recipes",
                to="library.sourcedocument",
            ),
        ),
        migrations.AddField(
            model_name="collectionrecipe",
            name="url_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forked_collection_recipes",
                to="library.urlrecipeimport",
            ),
        ),
        migrations.AddField(
            model_name="collectionrecipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectioningredientline",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_lines",
                to="collection.collectionrecipe",
            ),
        ),
        migrations.AddField(
            model_name="recipeboxitem",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_item",
                to="collection.collectionrecipe",
            ),
        ),
        migrations.AddField(
            model_name="recipeboxitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_box_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
