# Generated by Django 6.0.6 on 2026-06-19 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "default_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("teaspoon", "teaspoon"),
                            ("tablespoon", "tablespoon"),
                            ("fluid_ounce", "fluid ounce"),
                            ("cup", "cup"),
                            ("quart", "quart"),
                            ("gallon", "gallon"),
                            ("milliliter", "milliliter"),
                            ("liter", "liter"),
                            ("pound", "pound"),
                            ("ounce", "ounce"),
                            ("milligram", "milligram"),
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("inch", "inch"),
                            ("centimeter", "centimeter"),
                            ("whole", "whole"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "base_ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="catalog.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IngredientAlias",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias_name", models.CharField(max_length=255)),
                ("default_substitution_note", models.TextField(blank=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.ingredient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["alias_name"],
                "unique_together": {("user", "alias_name")},
            },
        ),
    ]
